- hosts: all
  remote_user: ec2-user
  become: yes
  vars:
    kube_apiserver_advertise_address: "{{ hostvars[groups['kube'][0]]['ansible_host'] }}"
  tasks:
  - name: Perform dnf update
    dnf:
       name: "*"
       state: latest
  - name: Install telnet
    dnf:
      name: telnet
      state: installed
  - name: Install nginx
    dnf:
       name: nginx
       state: installed
  - name: Delete existing nginx.conf
    file:
       path: /etc/nginx/nginx.conf
       state: absent
  - name: Copy new nginx.conf
    copy:
       src: /opt/ansible/nginx.conf
       dest: /etc/nginx/nginx.conf
  - name: Start Nginx
    service:
       name: nginx
       state: started
  - name: Enable nginx service
    systemd:
       name: nginx
       enabled: yes
       state: started
  - name: Install Docker
    dnf:
       name:
         - docker
       state: installed
  - name: Start Docker
    service:
       name: docker
       state: started
  - name: Enable Docker service
    systemd:
       name: docker
       enabled: yes
  - name: Create /etc/docker directory
    file:
       path: /etc/docker
       state: directory
  - name: Disable all swap space
    command: swapoff -a
  - name: Load br_netfilter kernel module
    command: modprobe br_netfilter
  - name: Add br_netfilter to modules-load.d
    copy:
       dest: /etc/modules-load.d/k8s.conf
       content: "br_netfilter\n"
  - name: Add k8s.conf to sysctl.d
    copy:
       dest: /etc/sysctl.d/k8s.conf
       content: |
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1a
  - name: Reload sysctl configuration
    command: sysctl --system
  - name: Copy Docker daemon.json file
    copy:
       content: |
         {
           "exec-opts": ["native.cgroupdriver=systemd"],
           "log-driver": "json-file",
           "log-opts": {
             "max-size": "100m"
           },
           "storage-driver": "overlay2"
         }
       dest: /etc/docker/daemon.jsona
  - name: Reload systemd configuration, restart Docker, enable at boot, and check status
    systemd:
       name: docker
       state: restarted
       enabled: yes
       daemon_reload: yes
  - name: Create Kubernetes repository configuration file
    copy:
       dest: /etc/yum.repos.d/kubernetes.repo
       content: |
         [kubernetes]
         name=Kubernetes
         baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
         enabled=1
         gpgcheck=1
         repo_gpgcheck=1
         gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  - name: Install Kubernetes components
    dnf:
       name:
         - kubelet
         - kubeadm
         - kubectl  
       state: present
  - name: Enable and start kubelet service
    systemd:
       name: kubelet
       enabled: yes
       state: started
  - name: Disable SELinux enforcement
    shell: setenforce 0
  - name: Modify /etc/selinux/config file
    lineinfile:
       path: /etc/selinux/config
       regexp: '^SELINUX=enforcing$'
       line: 'SELINUX=permissive'
       backup: yes





















